---
title: "Evaluating the Difference Between Manhattan and Brooklyn in Predicting the Full Market Value of New York City Condominiums"
author: Tomas Meade and Logan Hyde, statistical analysis by Tomas Meade
output:
  pdf_document: default
---


```{r}

#Import packages
library(tidyverse)
library(broom)
library(knitr)
library(dplyr)

#Read in data
condos <- read_csv("nyc-condos.csv")

#Create new column with only borough and convert to factor
condos$Boro <- substr(condos$`Boro-Block-Lot`, 0, 1)

condos$Boro <- factor(condos$Boro)

#Check amount of observations in each borough
sum(condos$Boro == "1")
sum(condos$Boro == "2")
sum(condos$Boro == "3")
sum(condos$Boro == "4")
sum(condos$Boro == "5")

#Remove all observations except those in Manhatten and Brooklyn
condos = filter(condos, Boro != "2" & Boro != "4" & Boro != "5")

#Variables of Interest:
#EstGrossIncome
#TotalUnits
#GrossSqFt
#EstimatedExpense
#Boro

```

```{r}

#Full MLR model
full <- lm(FullMarketValue ~ 
             EstGrossIncome + 
             TotalUnits + 
             GrossSqFt + 
             EstimatedExpense + 
             Boro, data = condos)
summary(full)

```

```{r}

#Scatter plot and SLR model for EstGrossIncome
condos %>% ggplot(aes(x=EstGrossIncome, y=FullMarketValue)) + geom_point()

slrIncome <- lm(FullMarketValue ~ EstGrossIncome, data = condos)
summary(slrIncome)

```

```{r}

#Scatter plot and SLR model for GrossSqFt
condos %>% ggplot(aes(x=GrossSqFt, y=FullMarketValue)) + geom_point()

slrSqFt <- lm(FullMarketValue ~ GrossSqFt, data = condos)
summary(slrSqFt)

```

```{r}

#Scatter plot and SLR model for EstimatedExpense
condos %>% ggplot(aes(x=EstimatedExpense, y=FullMarketValue)) + geom_point()

slrExpense <- lm(FullMarketValue ~ EstimatedExpense, data = condos)
summary(slrExpense)

```

```{r}

#Scatter plot and SLR model for TotalUnits
condos %>% ggplot(aes(x=TotalUnits, y=FullMarketValue)) + geom_point()

slrUnits <- lm(FullMarketValue ~ TotalUnits, data = condos)
summary(slrUnits)

```

```{r}

#Scatter plot and SLR model for Boro
condos %>% ggplot(aes(x=Boro, y=FullMarketValue)) + geom_point()

slrBoro <- lm(FullMarketValue ~ Boro, data = condos)
summary(slrBoro)

```


```{r}


#Create easily accesable summary statistics for SLR models
slrIncomeM <- tidy(slrIncome)

slrSqFtM <- tidy(slrSqFt)

slrUnitsM <- tidy(slrUnits)

slrExpenseM <- tidy(slrExpense)

slrBoroM <- tidy(slrBoro)

#Create dataframe of summary statistics for SLR models

Variable <- c('EstGrossIncome','TotalUnits','GrossSqFt', 'EstimatedExpense', 'Boro')

           
Coefficient <- c(round(as.numeric(slrIncomeM[2, "estimate"]), digits = 2), 
                 round(as.numeric(slrUnitsM[2, "estimate"]), digits = 2), 
                 round(as.numeric(slrSqFtM[2, "estimate"]), digits = 2), 
                 round(as.numeric(slrExpenseM[2, "estimate"]), digits = 2),
                 round(as.numeric(slrBoroM[2, "estimate"]), digits = 2))


P_value <- c(round(as.numeric(slrIncomeM[2, "p.value"]), digits = 3), 
             round(as.numeric(slrUnitsM[2, "p.value"]), digits = 3), 
             round(as.numeric(slrSqFtM[2, "p.value"]), digits = 3), 
             round(as.numeric(slrExpenseM[2, "p.value"]), digits = 3),
             round(as.numeric(slrBoroM[2, "p.value"]), digits = 6))

Intercept <- c(round(as.numeric(slrIncomeM[1, "estimate"]), digits = 2), 
                 round(as.numeric(slrUnitsM[1, "estimate"]), digits = 2), 
                 round(as.numeric(slrSqFtM[1, "estimate"]), digits = 2), 
                 round(as.numeric(slrExpenseM[1, "estimate"]), digits = 2),
                 round(as.numeric(slrBoroM[1, "estimate"]), digits = 2))



slr.df <- data.frame(Variable, Coefficient, Intercept, P_value)

names(slr.df)[names(slr.df) == "P_value"] <- "Approximate p-value"


```


```{r tab1}
#Create table of summary statistics for SLR models
kable(slr.df, caption = 'Each row represents an SLR model with the key predictor variable and the outcome variable full market value. Each predictor variable is listed along with its associated coefficient, intercept and p-value.', format = "markdown")

```



```{r fig1, fig.width=5,fig.height=4,fig.cap="\\label{fig:figs} Bootstrap Confidence Interval for the coefficient of borough location in the MLR model. The red dotted lines represent the bootstrap confidence interval and the green dotted line represents the estimate of the borough coefficient from the MLR model."}

# Function to get one bootstrap sample
# Inputs: data and number of observations you want in your bootstrap sample

resample <- function(data, resample_size) 
{
                    ## Randomly choose resample_size integers from 1 to the total number of rows in the data:
                    row_numbers <- sample.int(nrow(data), size=resample_size, replace=TRUE)
                    ## Create a data frame with those rows from the original data:
                    resample_data <- data[row_numbers,]
  return(resample_data)
}


# Set seed for reproducibility:
set.seed(16)


# Fit the model on it to get our slope estimates, and replicate that 1,000 times:
Results <- replicate(1000, 
                     lm(FullMarketValue ~ Boro + EstGrossIncome + TotalUnits + GrossSqFt + EstimatedExpense, 
                        data = resample(condos, resample_size=nrow(condos)))$coefficients)

# Transpose it
Boot_Res <- data.frame(t(Results))

# Calculate the mean, median, variance, std. deviation, etc. of these results:
Boro_Res <- with(Boot_Res, c(mean=mean(Boro3),
                            median = median(Boro3),
                            variance = var(Boro3),
                            stdev = sd(Boro3)))
                

# Get confidence intervals using the quantile function:
Boro_CI <- quantile(Boot_Res$Boro3, probs=c(0.025, 0.975))


# Plot a histogram of the bootstrap estimates with labels for the median, and the 95% CI of our observed estimate.
BS_Ests <- Boot_Res %>% ggplot(aes(x = Boro3)) + 
  geom_histogram(bins=30) + 
  geom_vline(xintercept = full$coefficients["Boro3"], 
             col = "green", lty = "dotted") + 
  labs(title = "Histogram of Bootstrap Estimates for Borough Coefficient", 
       x = expression(beta[1]), 
       y = "Count") + 
  theme_bw()

## Add in lines with the bootstrap CI:
BS_Ests <- BS_Ests + 
  geom_vline(xintercept = quantile(Boot_Res$Boro, probs=c(0.025,0.975)), 
             col = "red", 
             lty = "dashed") + 
  geom_label(x = 0.6, y = 200, label = "Bootstrap 95% CI", col = "red")

BS_Ests

```


